name = "kipos-plus-gr"
main = "worker.js"
compatibility_date = "2026-02-18"

[assets]
directory = "./dist"
binding = "ASSETS"

[vars]
CONTACT_TO = "adrkost@gmail.com"
MAIL_FROM = "Κήπος Plus <noreply@kiposplus.gr>"
