name = "kipos-plus-gr"
main = "worker.js"
compatibility_date = "2026-02-18"

[assets]
directory = "./dist"
binding = "ASSETS"

[vars]
RESEND_API_KEY = "re_4czzSTQA_6KYS1uV5ezemMLn8EurSPJ8j"
CONTACT_TO = "gregtsakma@gmail.com"
MAIL_FROM = "Kipos Plus <onboarding@resend.dev>"
